name: flutter_booking_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.0
  smooth_page_indicator: ^1.2.0+3
  auto_route: ^9.2.2
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  auto_route_generator: ^9.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/src/localization/
    - assets/animations/
